@startuml web-crawler-class
left to right direction
class UrlMessage {
  key: string
  url: URL 
  content?: string 
  hash?: string
  links?: string[]
  UrlMessage addContent(content: string)
  UrlMessage addHash(hash: string)
  UrlMessage addLinks(links: string[])
  UrlMessageInJSON toJSON()
  string toString()
  UrlMessageDebug toDebug()
}

class UrlScheduler extends stream.Duplex {
  -_maximumSizeOfBatch: readonly number;
  -_activeKeys: readonly Set<string>;
  -urlsWithLinks: readonly Record<string, string[]>;
  -outputFile?: readonly string;
  -logger?: readonly Logger;
  -_messagesForNextCall: readonly UrlMessage[];
  -_read(): void
  -_write(batch: UrlMessage[], _encoding: string, next: (error?: Error | null) => void): void
  -_final(next: (error?: Error | null) => void): void
}

class UrlDownloader extends stream.Transform {
  -logger?: readonly Logger;
  -delayMs: readonly number;
  -_transform(messages: UrlMessage[], _encoding: string, next: TransformCallback)
}

class HashGenerator extends stream.Transform {
  -logger?: readonly Logger;
  -_transform(messages: UrlMessage[], _encoding: string, next: TransformCallback)
}

class HashChecker extends stream.Transform {
  -logger?: readonly Logger;
  -_hashesSeen: Set<string>;
  -_transform(messages: UrlMessage[], _encoding: string, next: TransformCallback)
}

class ContentParser extends stream.Transform {
  -logger?: readonly Logger;
  -_transform(messages: UrlMessage[], _encoding: string, next: TransformCallback)
}

class LinkFilter extends stream.Transform {
  -_seedUrl: readonly URL;
  -_excludedPaths: readonly string[];
  -_seenLinks: Set<string>;
  -_logger?: readonly Logger;
  -_linkIsLocalAnchor(key: string, link: string): boolean
  -_linkIsForDifferentHostname(key: string, linkUrl: URL): boolean
  -_linkIsNotHTTP(key: string, linkUrl: URL): boolean
  -_linkIsInExcludedPaths(key: string, linkUrl: URL): boolean
  -_linkIsFile(key: string, linkUrl: URL): boolean
  -_transform(messages: UrlMessage[], _encoding: string, next: TransformCallback)
}

@enduml